services:
    api:
        build: ./TODO.Api
        ports:
            - "5000:8081"
        depends_on: 
            - database
    database:
        image: postgres:17.5
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: tQ8@Ejn6#pLxVd2RmZ9!KbFsY7*hG4wP
            POSTGRES_DB: TODODb
        ports:
            - "8001:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
volumes:
  db_data: