services:
    file-server:
        build:
            context: ./file-server
        ports:
            - "8080:80"
        volumes:
            - ./uploads:/usr/share/nginx/html/images
    api:
        build: ./TODO.Api
        ports:
            - "5000:8081"
        depends_on: 
            - database
        volumes:
            - ./uploads:/uploads
    database:
        image: postgres:17.5
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: tQ8@Ejn6#pLxVd2RmZ9!KbFsY7*hG4wP
            POSTGRES_DB: TODODb
        ports:
            - "8001:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
volumes:
  db_data: