services:
    minio:
        image: minio/minio
        container_name: minio
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: pQneK51#3~.
        command: server /data --console-address ":9001"
        volumes:
            - minio-data:/data
    api:
        build: ./TODO.Api
        ports:
            - "5000:8081"
        depends_on: 
            - database
        volumes:
            - ./uploads:/uploads
    database:
        image: postgres:17.5
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: tQ8@Ejn6#pLxVd2RmZ9!KbFsY7*hG4wP
            POSTGRES_DB: TODODb
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - "8001:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
volumes:
    minio-data:
    db_data: